security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        App\CoreBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        database_users:
            entity: { class: AppCoreBundle:User, property: username }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                provider: database_users
                check_path: /api/login_check
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

#        api:
#            pattern:   ^/api
#            stateless: true
#            lexik_jwt:
#                authorization_header:
#                    enabled: true
#                    prefix:  Bearer
#                query_parameter:
#                    enabled: true
#                    name:    bearer
            
        
#    access_control:
#        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
